### ISSUE TITLE
Invalid license (there is no public domain license in spdx)

### ISSUE THREAD

**Issue by mensfeld** [elebow/cchardet-ruby#1]
RubyGems core team recommends to use spdx licenses. There is no "public domain" license. https://guides.rubygems.org/specification-reference/#licenseo

ref https://github.com/elebow/cchardet-ruby/blob/trunk/cchardet.gemspec#L13

**Comment by elebow** [comment]
Thank you.

I have relicensed the gem under MIT License to reduce potential confusion.
