### ISSUE TITLE
RubyGems and Github naming mismatch

### ISSUE THREAD

**Issue by mensfeld** [elebow/cchardet-ruby#2]
Hey,

My name is Maciej Mensfeld and I run a research security project called diffend.io.

I've noticed, that you have a mismatch between the repo name on GitHub (https://github.com/elebow/cchardet-ruby) and the RubyGems one (https://rubygems.org/gems/cchardet).

This mismatch has been recently used as a brandjacking base for libraries like yours thus I took courtesy and "booked" it for you (if you want).

If not, I'll just keep it as it is, protecting the GH_NAME :)

If you want to transfer the ownership just please reach out to me.

Have a great day and thank you

ref https://rubygems.org/gems/cchardet https://github.com/elebow/cchardet-ruby

**Comment by elebow** [comment]
Thank you. I am happy to leave ownership of the placeholder with you.
